config/routes.rb
Rails.application.routes.draw do
  resources :onlines do
    resources :students
  end

  root "onlines#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/online.rb
class Online < ApplicationRecord
    has_many :students

    validates_presence_of :class_name, :hours_per_week
    validates :class_name, length: {minimum:1, maximum:8}
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :online

  validates_presence_of :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/onlines_controller.rb
class OnlinesController < ApplicationController
  before_action :set_online, only: [:show, :edit, :update, :destroy]

  # GET /onlines
  # GET /onlines.json
  def index
    @onlines = Online.all
  end

  # GET /onlines/1
  # GET /onlines/1.json
  def show
  end

  # GET /onlines/new
  def new
    @online = Online.new
  end

  # GET /onlines/1/edit
  def edit
  end

  # POST /onlines
  # POST /onlines.json
  def create
    @online = Online.new(online_params)

    respond_to do |format|
      if @online.save
        format.html { redirect_to @online, notice: 'Online was successfully created.' }
        format.json { render :show, status: :created, location: @online }
      else
        format.html { render :new }
        format.json { render json: @online.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onlines/1
  # PATCH/PUT /onlines/1.json
  def update
    respond_to do |format|
      if @online.update(online_params)
        format.html { redirect_to @online, notice: 'Online was successfully updated.' }
        format.json { render :show, status: :ok, location: @online }
      else
        format.html { render :edit }
        format.json { render json: @online.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onlines/1
  # DELETE /onlines/1.json
  def destroy
    @online.destroy
    respond_to do |format|
      format.html { redirect_to onlines_url, notice: 'Online was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_online
      @online = Online.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def online_params
      params.require(:online).permit(:class_name, :assignments, :hours_per_week)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def create
        @online = Online.find(params[:online_id])
            @student = @online.students.create(params[:student].permit(:name, :email, :here))
        redirect_to online_path(@online)
    end

    def destroy
        @online = Online.find(params[:online_id])
        @student = @online.students.find(params[:id])
        @student.destroy
        redirect_to online_path(@online)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/onlines_helper.rb
module OnlinesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/onlines/_form.html.erb
<%= form_with(model: online, local: true) do |form| %>
  <% if online.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(online.errors.count, "error") %> prohibited this online from being saved:</h2>

      <ul>
        <% online.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class_name %>
    <%= form.text_field :class_name %>
  </div>

  <div class="field">
    <%= form.label :assignments %>
    <%= form.check_box :assignments %>
  </div>

  <div class="field">
    <%= form.label :hours_per_week %>
    <%= form.number_field :hours_per_week %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/onlines/edit.html.erb
<h1>Editing Online</h1>

<%= render 'form', online: @online %>

<%= link_to 'Show', @online %> |
<%= link_to 'Back', onlines_path %>

app/views/onlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Onlines</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Assignments</th>
      <th>Hours per week</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @onlines.each do |online| %>
      <tr>
        <td><%= online.class_name %></td>
        <td><%= online.assignments %></td>
        <td><%= online.hours_per_week %></td>
        <td><%= link_to 'Show', online %></td>
        <td><%= link_to 'Edit', edit_online_path(online) %></td>
        <td><%= link_to 'Destroy', online, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Online', new_online_path %>

app/views/onlines/new.html.erb
<h1>New Online</h1>

<%= render 'form', online: @online %>

<%= link_to 'Back', onlines_path %>

app/views/onlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @online.class_name %>
</p>

<p>
  <strong>Assignments:</strong>
  <%= @online.assignments %>
</p>

<p>
  <strong>Hours per week:</strong>
  <%= @online.hours_per_week %>
</p>

</div>
<div id="todo_items_wrapper">
  <h2> Students Listed Below</h2>
 <%= render @online.students %>
 <hr />
 <h2>Add Student</h2>
 <div id="form">
  <%= render "students/form" %>
 </div>
</div>

<%= link_to 'Edit', edit_online_path(@online) %> |
<%= link_to 'Back', onlines_path %>

app/views/students/_form.html.erb
<%= form_for([@online, @online.students.build]) do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field(:name, {:class => 'form-control'} ) %>
    </p>
    
    <p>
        <%= f.label :email %><br>
        <%= f.text_area( :email, {:class => 'form-control'} )%>
    </p>
    
    <p>
        <%= f.label :here %><br>
        <%= f.check_box( :here, {:class => 'form-control'} ) %>
        
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-defualt'}) %>
    </p>
<% end %>

app/views/students/_student.html.erb
<div class="content">
    <p>
        Name: <%= student.name %>
        <br>
        Email: <%= student.email%>
        <br>
        
        Present: <%= student.here%>
    </p>
    <%= link_to "Remove", online_student_path(@online, student.id), method: :delete, data: { confirm: "Are you sure?" } %>
</div>